### ISSUE TITLE
camxoverridesettings.txt location

### ISSUE THREAD

**Issue by Uzver123** [sean6541/op9_series_camera_unlocker#1]
Hello i am puzzled to where is camxoverridesettings.txt located i can't seem to find it in source code.

**Comment by sean6541** [comment]
camxoverridesettings.txt is located at `/vendor/etc/camera/camxoverridesettings.txt`. On the OnePlus 9 series, it doesn't exist by default on the current firmware, but it can be added using Magisk. Take a look at this modules `post-fs-data.sh` script. It looks for an existing camxoverridesettings.txt file and copies it to a temporary directory (or creates a blank file if camxoverridesettings.txt doesn't exist) along with a modified camxoverridesettings.txt that has the necessary definitions added to enable 48MP. When you toggle 48MP with the app or commands, the module is just switching between these two versions of camxoverridesettings.txt by coping the appropriate one to `<module directory>/system/vendor/etc/camera/camxoverridesettings.txt` and then restarting the camera stack and purging cache.

**Comment by sean6541** [comment]
The `system/vendor/etc/camera` directories in the module are created by the `post-fs-data.sh` script.

**Comment by Uzver123** [comment]
Thanks for clarification
